[versions]
kotlin = "2.2.0"
lifecycle = "2.9.1"
compose-multiplatform = "1.9.0-beta03"
compose-navigation = "2.9.0-beta05"

detekt = "1.23.8"

# Test dependencies
junit = "4.13.2"

[libraries]
# Lifecycle
lifecycle-viewmodel-compose = { module = "org.jetbrains.androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "lifecycle" }
lifecycle-runtime-compose = { module = "org.jetbrains.androidx.lifecycle:lifecycle-runtime-compose", version.ref = "lifecycle" }

# Compose Navigation (Multiplatform compatible)
navigation-compose = { module = "org.jetbrains.androidx.navigation:navigation-compose", version.ref = "compose-navigation" }

# Detekt Formatting
detekt-formatting = { module = "io.gitlab.arturbosch.detekt:detekt-formatting", version.ref = "detekt" }

# Test dependencies
junit = { module = "junit:junit", version.ref = "junit" }
kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test", version.ref = "kotlin" }
kotlin-test-junit = { module = "org.jetbrains.kotlin:kotlin-test-junit", version.ref = "kotlin" }

# ================================================================
# Dependencies of the included build-logic
# ================================================================
kotlin-gradle-plugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version =  "1.9.0"}
compose-compiler-gradle-plugin = { module = "org.jetbrains.kotlin:compose-compiler-gradle-plugin", version.ref = "kotlin" }
compose-gradle-plugin = { module = "org.jetbrains.compose:compose-gradle-plugin", version.ref = "compose-multiplatform" }

# Detekt
detekt-gradle-plugin = { module = "io.gitlab.arturbosch.detekt:detekt-gradle-plugin", version.ref = "detekt" }

[plugins]
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
compose-multiplatform = { id = "org.jetbrains.compose", version.ref = "compose-multiplatform" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }

# Detekt
detekt = { id = "io.gitlab.arturbosch.detekt", version.ref = "detekt" }

# ================================================================
#  Plugins defined by this project
# ================================================================
app-kotlin = { id = "app.kotlin" }
app-compose = { id = "app.compose" }
app-detekt = { id = "app.detekt" }
